name: Scrape
on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 15 * * 1-5'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Scrape
      run: npm run scrape
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
        BRANCH_NAME: main
